#!/bin/bash
export LIBGL_ALWAYS_INDIRECT=1
export LIBGL_ALWAYS_SOFTWARE=0
export MESA_GL_VERSION_OVERRIDE=3.0
PROFILEDIR="${HOME}/dev/vscodium"

if [ -d "${PROFILEDIR}" ] ; then
    docker run -it \
    	   --rm \
	   --name vscodium \
	   --net=host \
	   --env="DISPLAY" \
	   --mount "type=bind,src=${HOME}/.Xauthority,dst=/home/vscodium/.Xauthority,readonly" \
 	   --mount "type=bind,src=${PROFILEDIR},dst=/home/vscodium" \
	   andzuc/debian-vscodium:1.56.2 \
	   "$@"
else
    echo "Profile not found: ${PROFILE}"
fi
# unused run options
# --security-opt seccomp=chrome.json \
    # --ipc private \
    # --shm-size 2g \
    # --env="LIBGL_ALWAYS_INDIRECT" \
    # --env="LIBGL_ALWAYS_SOFTWARE" \
    # --env="MESA_GL_VERSION_OVERRIDE" \
